AWSTemplateFormatVersion: 2010-09-09
Resources:
  rdsVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags: 
        - Key : purpose
          Value: rds
Outputs:
   rdsVpc:
    Description: The ID of the VPC
    Value: !Ref rdsVpc
    Export:
      Name: rds-vpc-id
 